### PR TITLE
Expose more information to serializers

### PR DESCRIPTION
**Pull request by spaceone**
See https://github.com/luizalabs/shared-memory-dict/pull/32#issuecomment-952643475

### CODE REVIEW

**Comment by spaceone** [comment]
Even better would be to not change the function signature but just initialize the Serializer class with a reference to self.
currently it expects a instantiated class.

**Comment by spaceone** [comment]
Workaround would be to wrap shared memory dict like:
```
def dict(name, size):
    serializer = MySerializer()
    smd = SharedMemoryDict(name, size, serializer=serializer)
    serializer.smd = smd
    serializer.name = name
    return smd
```

**Comment by spaceone** [comment]
I don't necessarily need this.

I found a approach with subclassing, see:
https://github.com/spaceone/shared-memory-dict/blob/json-nested-dictionary-serializer/shared_memory_dict/nested_json_serializer.py

**Comment by thyagomininelli** [comment]
Hi, @spaceone . We mantainers decided add in README https://github.com/luizalabs/shared-memory-dict/pull/32#issuecomment-949993100.
Perhaps, you can open a new issue to explain propose. OK?
Thank you for contribution!

**Pull request closed without merging**
